package de.netzwerk_universitaetsmedizin.codex.processes.tools.generator;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;
import java.util.Properties;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import de.netzwerk_universitaetsmedizin.codex.processes.tools.generator.CertificateGenerator.CertificateFiles;

public class ConfigGenerator
{
	private static final Logger logger = LoggerFactory.getLogger(ConfigGenerator.class);

	private Properties dockerDicFhirConfigProperties;
	private Properties dockerCrrFhirConfigProperties;
	private Properties dockerGthFhirConfigProperties;

	private Properties readProperties(Path propertiesFile)
	{
		Properties properties = new Properties();
		try (InputStream in = Files.newInputStream(propertiesFile);
				InputStreamReader reader = new InputStreamReader(in, StandardCharsets.UTF_8))
		{
			properties.load(reader);
		}
		catch (IOException e)
		{
			logger.error("Error while reading properties from " + propertiesFile.toString(), e);
			throw new RuntimeException(e);
		}
		return properties;
	}

	private void writeProperties(Path propertiesFiles, Properties properties)
	{
		try (OutputStream out = Files.newOutputStream(propertiesFiles);
				OutputStreamWriter writer = new OutputStreamWriter(out, StandardCharsets.UTF_8))
		{
			properties.store(writer, "Generated by test-data-generator");
		}
		catch (IOException e)
		{
			logger.error("Error while writing properties to " + propertiesFiles.toString(), e);
			throw new RuntimeException(e);
		}
	}

	public void modifyDockerTestFhirConfigProperties(Map<String, CertificateFiles> clientCertificateFilesByCommonName)
	{
		modifyDockerDicFhirConfigProperties(clientCertificateFilesByCommonName);
		modifyDockerCrrFhirConfigProperties(clientCertificateFilesByCommonName);
		modifyDockerGthFhirConfigProperties(clientCertificateFilesByCommonName);
	}

	private void modifyDockerDicFhirConfigProperties(Map<String, CertificateFiles> clientCertificateFilesByCommonName)
	{
		CertificateFiles dicClient = clientCertificateFilesByCommonName.get("dic-client");
		CertificateFiles webbrowserTestUser = clientCertificateFilesByCommonName.get("Webbrowser Test User");

		Path dockerTestFhirConfigTemplateFile = Paths
				.get("src/main/resources/config-templates/docker-test-dic-fhir-config.properties");
		dockerDicFhirConfigProperties = readProperties(dockerTestFhirConfigTemplateFile);
		dockerDicFhirConfigProperties.setProperty("org.highmed.dsf.fhir.local-user.thumbprints",
				dicClient.getCertificateSha512ThumbprintHex() + ","
						+ webbrowserTestUser.getCertificateSha512ThumbprintHex());

		writeProperties(Paths.get("config/docker-test-dic-fhir-config.properties"), dockerDicFhirConfigProperties);
	}

	private void modifyDockerCrrFhirConfigProperties(Map<String, CertificateFiles> clientCertificateFilesByCommonName)
	{
		CertificateFiles crrClient = clientCertificateFilesByCommonName.get("crr-client");
		CertificateFiles webbrowserTestUser = clientCertificateFilesByCommonName.get("Webbrowser Test User");

		Path dockerTestFhirConfigTemplateFile = Paths
				.get("src/main/resources/config-templates/docker-test-crr-fhir-config.properties");
		dockerCrrFhirConfigProperties = readProperties(dockerTestFhirConfigTemplateFile);
		dockerCrrFhirConfigProperties.setProperty("org.highmed.dsf.fhir.local-user.thumbprints",
				crrClient.getCertificateSha512ThumbprintHex() + ","
						+ webbrowserTestUser.getCertificateSha512ThumbprintHex());

		writeProperties(Paths.get("config/docker-test-crr-fhir-config.properties"), dockerCrrFhirConfigProperties);
	}

	private void modifyDockerGthFhirConfigProperties(Map<String, CertificateFiles> clientCertificateFilesByCommonName)
	{
		CertificateFiles gthClient = clientCertificateFilesByCommonName.get("gth-client");
		CertificateFiles webbrowserTestUser = clientCertificateFilesByCommonName.get("Webbrowser Test User");

		Path dockerTestFhirConfigTemplateFile = Paths
				.get("src/main/resources/config-templates/docker-test-gth-fhir-config.properties");
		dockerGthFhirConfigProperties = readProperties(dockerTestFhirConfigTemplateFile);
		dockerGthFhirConfigProperties.setProperty("org.highmed.dsf.fhir.local-user.thumbprints",
				gthClient.getCertificateSha512ThumbprintHex() + ","
						+ webbrowserTestUser.getCertificateSha512ThumbprintHex());

		writeProperties(Paths.get("config/docker-test-gth-fhir-config.properties"), dockerGthFhirConfigProperties);
	}

	public void copyDockerTestFhirConfigProperties()
	{
		Path dockerMedic1FhirConfigPropertiesFile = Paths
				.get("../codex-processes-ap1-docker-test-setup/dic/fhir/app/conf/config.properties");
		logger.info("Copying config.properties to {}", dockerMedic1FhirConfigPropertiesFile);
		writeProperties(dockerMedic1FhirConfigPropertiesFile, dockerDicFhirConfigProperties);

		Path dockerMedic2FhirConfigPropertiesFile = Paths
				.get("../codex-processes-ap1-docker-test-setup/crr/fhir/app/conf/config.properties");
		logger.info("Copying config.properties to {}", dockerMedic2FhirConfigPropertiesFile);
		writeProperties(dockerMedic2FhirConfigPropertiesFile, dockerCrrFhirConfigProperties);

		Path dockerTtpFhirConfigPropertiesFile = Paths
				.get("../codex-processes-ap1-docker-test-setup/gth/fhir/app/conf/config.properties");
		logger.info("Copying config.properties to {}", dockerTtpFhirConfigPropertiesFile);
		writeProperties(dockerTtpFhirConfigPropertiesFile, dockerGthFhirConfigProperties);

	}
}
